### ISSUE TITLE
Memberships

### ISSUE THREAD

**Issue by Sirhexalot** [TZK-/TaigaPHP#9]
Hello can you add Memberships?

`<?php

namespace TZK\Taiga\Services;

use TZK\Taiga\RestClient;
use TZK\Taiga\Service;

class Memberships extends Service
{
    public function __construct(RestClient $taiga)
    {
        parent::__construct($taiga, 'memberships');
    }

    public function create(array $data)
    {
        $this->post(null, [], $data);
    }
}
`

**Comment by TZK-** [comment]
Hello,
Can you do a pull request for this ?

**Comment by Sirhexalot** [comment]
I will do that on Monday
